# Generated by Django 3.1 on 2020-12-03 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangePassword',
            fields=[
                ('id_cp', models.AutoField(primary_key=True, serialize=False)),
                ('idlink', models.CharField(max_length=16, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('generated', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
