# Generated by Django 3.1 on 2020-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_changepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changepassword',
            name='idlink',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
