# Generated by Django 3.1 on 2020-10-13 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='productCombo',
        ),
        migrations.AddField(
            model_name='combo',
            name='productCombo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='products.product'),
            preserve_default=False,
        ),
    ]
