# Generated by Django 3.1 on 2020-11-17 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='imageCombo',
            field=models.CharField(default='https://firebasestorage.googleapis.com/v0/b/hyperfoods-images.appspot.com/o/tenant1%2Fimages%2F2.png?alt=media', max_length=255),
            preserve_default=False,
        ),
    ]
