# Generated by Django 3.1 on 2020-10-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('combos', '0002_auto_20201012_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='productCombo',
        ),
        migrations.AddField(
            model_name='combo',
            name='productCombo',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
