# Generated by Django 3.1 on 2020-10-13 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0003_auto_20201012_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='discountCombo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
