# Generated by Django 3.1 on 2020-10-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0004_combo_discountcombo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='discountCombo',
            field=models.PositiveIntegerField(),
        ),
    ]
