# Generated by Django 3.1 on 2020-11-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('codeIngredient', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameIngredient', models.CharField(max_length=255)),
                ('priceIngredient', models.PositiveIntegerField()),
                ('additionalIngredient', models.BooleanField()),
            ],
        ),
    ]
