# Generated by Django 3.1 on 2020-11-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredientProduct',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
    ]
