# Generated by Django 3.1 on 2020-11-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageProduct',
            field=models.FileField(upload_to=''),
        ),
    ]
