# Generated by Django 3.1 on 2020-11-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201116_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageProduct',
            field=models.CharField(max_length=255),
        ),
    ]
