# Generated by Django 3.1 on 2020-11-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('combos', '0002_combo_imagecombo'),
        ('invoices', '0001_initial'),
        ('products', '0003_auto_20201116_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('codeInvoiceDetail', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityInvoiceDetail', models.PositiveIntegerField()),
                ('subtotalInvoiceDetail', models.PositiveIntegerField()),
                ('comboInvoiceDetail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='combos.combo')),
                ('invoiceInvoiceDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice')),
                ('productInvoiceDetail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
