# Generated by Django 3.1 on 2020-11-17 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combos', '0002_combo_imagecombo'),
        ('products', '0003_auto_20201116_2124'),
        ('invoiceDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetail',
            name='comboInvoiceDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='combos.combo'),
        ),
        migrations.AlterField(
            model_name='invoicedetail',
            name='productInvoiceDetail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
