# Generated by Django 3.1 on 2020-11-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
        ('invoiceDetails', '0002_auto_20201117_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetail',
            name='ingredientInvoiceDetail',
            field=models.ManyToManyField(to='ingredients.Ingredient'),
        ),
    ]
