# Generated by Django 3.1 on 2020-11-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceDetails', '0004_auto_20201118_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetail',
            name='invoiceInvoiceDetail',
        ),
    ]
