# Generated by Django 3.1 on 2020-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceDetails', '0005_remove_invoicedetail_invoiceinvoicedetail'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='detailInvoice',
            field=models.ManyToManyField(to='invoiceDetails.InvoiceDetail'),
        ),
    ]
