# Generated by Django 3.1 on 2020-12-08 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='type_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'basic'), (2, 'medium'), (3, 'full')], default=1),
        ),
    ]
