# Generated by Django 3.1 on 2020-12-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_auto_20201208_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type_plan',
            field=models.PositiveSmallIntegerField(choices=[(1, 'basic'), (2, 'medium'), (3, 'full')]),
        ),
    ]
