export const SET_CREDENTIALS = "SET_CREDENTIALS";
export const SET_SIDEBAR_OPENED = "SET_SIDEBAR_OPENED";
export const SET_BGCOLOR = "SET_BGCOLOR";
export const SET_MODE = "SET_MODE";
export const SET_NETWORKSTATUS = "SET_NETWORKSTATUS";
export const ADD_PENDING_WORKERS = "ADD_PENDING_WORKERS";